simulate error

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -30,7 +30,10 @@ jobs:
       - name: Coverage Report
         if: always() # Also generate the report if tests are failing
         continue-on-error: true
-        uses: davelosert/vitest-coverage-report-action@v2
+        # uses: davelosert/vitest-coverage-report-action@v2
+        run: |
+          echo "This step is intentionally broken to throw an error"
+          exit 1
 
       - name: E2E Tests
         run: npm run e2e
